### ISSUE TITLE
iOS 11 not working using iPhone 6S

### ISSUE THREAD

**Issue by YHSX88** [asus4/unity-taptic-plugin#1]
Hi 

I tried it but it was not working.

Any ideas ?

**Comment by asus4** [comment]
Hi @YHSX88 

I haven't tried on iOS11 yet.
But, Taptic API works only on iPhone7, iPhone7 Plus, iPhone8.

**Comment by Olden** [comment]
here about iphone 6s: https://medium.com/nerdmade/ios-haptic-feedback-for-iphone-7-and-6s-1bc6e7f1c285
