### ISSUE TITLE
Readme or instructions

### ISSUE THREAD

**Issue by cobear25** [asus4/unity-taptic-plugin#3]
How do you get this running in a project?

**Comment by asus4** [comment]
@cobear25  This runs only on actual iOS devices. It doesn't work on Editor. 

Add 2 scenes in BuildSetting to test the sample project
-  UnityTapticPlugin/Assets/TapticPlugin/Samples/Sample Ball.unity
-  UnityTapticPlugin/Assets/TapticPlugin/Samples/Sample UI.unity

And Build and Run on your iPhone.
